In [1]:
import numpy as np

In [3]:
arr = np.array([[2,4,5],
            [5,6,7]])

In [4]:
print('Array is of type: ',type(arr))

Array is of type:  <class 'numpy.ndarray'>


In [5]:
print('No. of Dimensions:', arr.ndim)

No. of Dimensions: 2


In [6]:
print('shape of array:',arr.shape)

shape of array: (2, 3)


In [7]:
arr.size

6

In [8]:
arr.dtype

dtype('int32')

In [13]:
np.arange(0,25,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [14]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
a = np.array([[1,3,5],[2,4,6],[9,7,5]], dtype = 'float')

In [16]:
a

array([[1., 3., 5.],
       [2., 4., 6.],
       [9., 7., 5.]])

In [21]:
b = np.array(((2,4,9,6),(2,6,4,7)))

In [24]:
b

array([[2, 4, 9, 6],
       [2, 6, 4, 7]])

In [26]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.full((3,4),25)

array([[25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25]])

In [28]:
np.full((4,4),6,dtype = 'complex')

array([[6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j],
       [6.+0.j, 6.+0.j, 6.+0.j, 6.+0.j]])

In [31]:
np.random.rand(3,3)

array([[0.6494207 , 0.32570872, 0.98390415],
       [0.31779667, 0.12165535, 0.77284973],
       [0.99032545, 0.60243284, 0.00594021]])

In [37]:
np.random.randint(5,50, size = (3,3))

array([[36, 41, 47],
       [ 6, 27, 41],
       [ 6,  7, 26]])

In [39]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [40]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [41]:
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
 
newarr = arr.reshape(2, 2, 3)

In [42]:
newarr

array([[[1, 2, 3],
        [4, 5, 2]],

       [[4, 2, 1],
        [2, 0, 1]]])

In [43]:
arr.reshape(4,3)

array([[1, 2, 3],
       [4, 5, 2],
       [4, 2, 1],
       [2, 0, 1]])

In [44]:
arr.reshape(3,4)

array([[1, 2, 3, 4],
       [5, 2, 4, 2],
       [1, 2, 0, 1]])

In [45]:
arr.reshape(1,12)

array([[1, 2, 3, 4, 5, 2, 4, 2, 1, 2, 0, 1]])

In [46]:
arr.reshape(12,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [4],
       [2],
       [1],
       [2],
       [0],
       [1]])

In [47]:
arr = np.array([[-1,2,5,4],
               [2,-5,0,4],
               [0,6,7,9],
               [-7,5,9,3]])

In [48]:
arr

array([[-1,  2,  5,  4],
       [ 2, -5,  0,  4],
       [ 0,  6,  7,  9],
       [-7,  5,  9,  3]])

In [57]:
temp = arr[:3,::2]              # arr[for Row[start:end:step],  for Col[start;end:step]]

In [58]:
temp

array([[-1,  5],
       [ 2,  0],
       [ 0,  7]])

In [69]:
arr[:2,0::3]

array([[-1,  4],
       [ 2,  4]])

In [73]:
arr

array([[-1,  2,  5,  4],
       [ 2, -5,  0,  4],
       [ 0,  6,  7,  9],
       [-7,  5,  9,  3]])

In [71]:
temp = arr[[0,1,2,3],[3,2,1,0]]    # index as (0,3) = 4, (1,2)=0, (2,1)=6, (3,0)=0

In [72]:
temp

array([ 4,  0,  6, -7])

In [78]:
cond = arr > 0

In [79]:
cond

array([[False,  True,  True,  True],
       [ True, False, False,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])