In [1]:
import numpy as np

In [2]:
x = [[1,2,3],[6,5,4],[7,5,6]]

In [3]:
df = np.array(x)

In [6]:
df

array([[1, 2, 3],
       [6, 5, 4],
       [7, 5, 6]])

In [7]:
df.dtype

dtype('int32')

In [8]:
df.shape

(3, 3)

In [10]:
df.size

9

In [12]:
df.ndim

2

In [14]:
zeros = np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
new_zero = np.zeros((3,3))

In [26]:
new_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
new_zero.dtype

dtype('float64')

In [28]:
new_zero.shape

(3, 3)

In [20]:
new_zero.size

9

In [21]:
new_zero.ndim

2

In [29]:
rng = np.arange(15)

In [30]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
rng1 = np.arange(15)

In [38]:
rng1.ndim

1

In [39]:
rng1.dtype

dtype('int32')

In [40]:
arr = [[2,6,9],[11,12,10],[15,24,7]]

In [45]:
new_arr = np.array(arr)

In [46]:
new_arr

array([[ 2,  6,  9],
       [11, 12, 10],
       [15, 24,  7]])

In [47]:
new_arr.sum(axis=0)

array([28, 42, 26])

In [48]:
new_arr.sum(axis=1)     

array([17, 33, 46])

In [49]:
new_arr.T                # Transpose of new_arr

array([[ 2, 11, 15],
       [ 6, 12, 24],
       [ 9, 10,  7]])

In [54]:
new_arr.nbytes

36

In [55]:
new_arr.max()        # find max value

24

In [56]:
new_arr.min()        # find min value

2

In [58]:
new_arr.sum()

96

In [61]:
new_arr

array([[ 2,  6,  9],
       [11, 12, 10],
       [15, 24,  7]])

In [62]:
new_arr.argmax()    # find max value index number

7

In [64]:
new_arr.argmin()       # find min value index number

0

In [68]:
new_arr[0]            # value fetch by index number

array([2, 6, 9])

In [72]:
temp = np.array([2,5,44,66,58,52,12,35,54,95,65])

In [73]:
temp

array([ 2,  5, 44, 66, 58, 52, 12, 35, 54, 95, 65])

In [74]:
temp[5]               # value fetch by index number

52

In [75]:
new_arr

array([[ 2,  6,  9],
       [11, 12, 10],
       [15, 24,  7]])

In [76]:
new_arr[1,:]

array([11, 12, 10])

In [77]:
new_arr[1]

array([11, 12, 10])

In [79]:
new_arr

array([[ 2,  6,  9],
       [11, 12, 10],
       [15, 24,  7]])

In [78]:
new_arr[1,1]       # access element 12 from array by using row index 1 and column index 1

12

In [80]:
a = np.array([[[24,12,10],[2,3,8],[66,15,4]]])

In [81]:
a.ndim            # 3 dimensional data

3

In [82]:
b =  np.array([[[[24,12,10],[2,3,8],[66,15,4]]]])

In [84]:
b.ndim            # 4 dimensional data

4

In [85]:
b

array([[[[24, 12, 10],
         [ 2,  3,  8],
         [66, 15,  4]]]])

In [89]:
c = np.array([[[21,23,25],[1,2,3]],[[24,56,54],[65,41,42]]])

In [90]:
c

array([[[21, 23, 25],
        [ 1,  2,  3]],

       [[24, 56, 54],
        [65, 41, 42]]])

In [91]:
c[0,1,1]

2

In [92]:
c.ndim

3

In [100]:
d = np.ones((2,2,2), dtype = 'int')

In [101]:
d.ndim

3

In [102]:
d

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [103]:
e = np.ones((4,4), dtype = 'int')     # 4x4 matrix and value is 1

In [106]:
e

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [109]:
np.zeros((4,4),dtype = 'int')     # matrix by 4x4 and value is zero

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [119]:
np.full((4,4), 25)          # matrix by 4x4 and value is 25

array([[25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25],
       [25, 25, 25, 25]])

In [120]:
np.random.rand(3,3)     # random value with matrix 3x3

array([[0.44309799, 0.73943979, 0.31201324],
       [0.90095118, 0.42008808, 0.22798578],
       [0.96942701, 0.48821036, 0.77475937]])

In [123]:
np.random.randint(10,50, size = (4,4))      # value range from 10 to 50 randomly with matrix 4x4

array([[40, 23, 40, 47],
       [42, 35, 24, 12],
       [30, 10, 47, 28],
       [15, 40, 19, 30]])

In [124]:
np.identity(4)                     # identity matrix, diagonaly value is 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [125]:
e

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [126]:
e*10         # value of e matrix multiply by 10

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [127]:
e/10           # value of e matrix devide by 10

array([[0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1],
       [0.1, 0.1, 0.1, 0.1]])

In [128]:
e+50            # value of e matrix added by 10

array([[51, 51, 51, 51],
       [51, 51, 51, 51],
       [51, 51, 51, 51],
       [51, 51, 51, 51]])

In [134]:
np.full((4,4),25)+25

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [135]:
temp1 = np.random.randint(10,50, size = (4,4))  

In [136]:
temp1

array([[16, 44, 23, 30],
       [36, 30, 31, 27],
       [17, 14, 36, 42],
       [38, 38, 24, 35]])

In [137]:
temp1.max()    # max value     method--1

44

In [138]:
np.max(temp1)    # max value    method--2

44

In [139]:
np.min(temp1)     # min value

14

In [140]:
temp.sum()     # sum value  method--1

488

In [141]:
np.sum(temp)    # sum value  method--2

488

In [146]:
temp1.argmin()  # min value location number

9

In [147]:
temp1.argmax()    # max value location number

1

In [148]:
temp1

array([[16, 44, 23, 30],
       [36, 30, 31, 27],
       [17, 14, 36, 42],
       [38, 38, 24, 35]])

In [153]:
# reshape in size

temp1.reshape(1,16)

array([[16, 44, 23, 30, 36, 30, 31, 27, 17, 14, 36, 42, 38, 38, 24, 35]])

In [154]:
temp1.reshape(16,1)

array([[16],
       [44],
       [23],
       [30],
       [36],
       [30],
       [31],
       [27],
       [17],
       [14],
       [36],
       [42],
       [38],
       [38],
       [24],
       [35]])

In [155]:
m = np.array([25,65,45,18,177,6985,145,22,35,65])

In [158]:
np.where(m>45)      # find index number greater than 45 values

(array([1, 4, 5, 6, 9], dtype=int64),)