In [1]:
import numpy as np

In [2]:
a = np.array([23,454,24,78,996,524,655,235])

In [3]:
a

array([ 23, 454,  24,  78, 996, 524, 655, 235])

In [4]:
type(a)

numpy.ndarray

In [5]:
a[5]

524

In [6]:
a[2]

24

In [19]:
lst = np.array([[2,4,5,7,9],[1,3,7,5,4]],dtype = 'int64')

In [20]:
lst

array([[2, 4, 5, 7, 9],
       [1, 3, 7, 5, 4]], dtype=int64)

In [21]:
type(lst)

numpy.ndarray

In [22]:
lst.shape

(2, 5)

In [23]:
lst.dtype

dtype('int64')

In [24]:
lst.itemsize    # size of 1 items like 1 items = 8 bytes

8

In [25]:
lst.size        # total no of counts

10

In [26]:
lst.itemsize * lst.size      # total size in bytes

80

In [27]:
temp = [2,5,6,8,4]

In [28]:
temp

[2, 5, 6, 8, 4]

In [29]:
import sys

In [30]:
sys.getsizeof(6)

28

In [31]:
sys.getsizeof(temp)

120

In [32]:
sys.getsizeof(6)*len(temp)

140

In [34]:
lst.ndim

2

In [73]:
lst = np.array([[[1,5,7],[2,3,8]],[[4,6,8],[6,8,7]]])

In [74]:
lst

array([[[1, 5, 7],
        [2, 3, 8]],

       [[4, 6, 8],
        [6, 8, 7]]])

In [75]:
lst.ndim

3

In [76]:
lst.dtype

dtype('int32')

In [77]:
type(lst)

numpy.ndarray

In [60]:
lst[0,1,2]

8

In [66]:
lst[0,1:]

array([[2, 3, 8],
       [4, 6, 8],
       [6, 8, 7]])

In [69]:
a = np.array([[12,45,23,54],[21,52,3,66]])

In [70]:
a

array([[12, 45, 23, 54],
       [21, 52,  3, 66]])

In [71]:
a[1,1]

52

In [72]:
a.ndim

2

In [78]:
lst

array([[[1, 5, 7],
        [2, 3, 8]],

       [[4, 6, 8],
        [6, 8, 7]]])

In [79]:
lst[1,1,2]

7

In [80]:
lst[1,1,0]

6

In [87]:
ls = np.ones([2,2],dtype = 'int')

In [88]:
ls

array([[1, 1],
       [1, 1]])

In [94]:
ls = np.ones((2,1,2,3),dtype = 'int')

In [95]:
ls

array([[[[1, 1, 1],
         [1, 1, 1]]],


       [[[1, 1, 1],
         [1, 1, 1]]]])

In [96]:
ls.ndim

4

In [103]:
ls = np.ones((4,3),dtype = 'int')

In [104]:
ls

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [105]:
np.ones((4,4),dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [106]:
np.zeros((3,4),dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [108]:
np.full((2,5),10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [109]:
np.full((4,3),15)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [110]:
np.random.rand(4,3)

array([[0.5832909 , 0.08778372, 0.10838672],
       [0.76608063, 0.10121709, 0.87686521],
       [0.06342384, 0.07935008, 0.90488847],
       [0.87942926, 0.60691641, 0.86859347]])

In [112]:
np.random.randint(5,9,size = (4,3))

array([[7, 5, 5],
       [8, 6, 5],
       [6, 7, 5],
       [5, 6, 7]])

In [117]:
lsr = np.random.randint(200,350,size = (4,3))

In [118]:
lsr

array([[310, 220, 326],
       [249, 287, 327],
       [251, 329, 276],
       [341, 334, 283]])

In [119]:
lsr.max()

341

In [120]:
lsr.min()

220

In [122]:
np.identity(4,dtype = 'int')

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [123]:
np.identity(5,dtype = 'int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

SyntaxError: invalid syntax (2994802235.py, line 1)

In [128]:
np.max(lsr)

341

In [129]:
np.min(lsr)

220

In [130]:
np.min(lsr) == lsr.min()

True

In [131]:
lsr.sum()

3533

In [132]:
lsr.argmax()

9

In [133]:
lsr

array([[310, 220, 326],
       [249, 287, 327],
       [251, 329, 276],
       [341, 334, 283]])

In [134]:
lsr.argmin()

1

In [135]:
np.argmax(lsr)

9

In [136]:
np.argmin(lsr)

1

In [137]:
lsr.reshape(1,12)

array([[310, 220, 326, 249, 287, 327, 251, 329, 276, 341, 334, 283]])

In [138]:
lsr.reshape(12,1)

array([[310],
       [220],
       [326],
       [249],
       [287],
       [327],
       [251],
       [329],
       [276],
       [341],
       [334],
       [283]])

In [139]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [140]:
np.where(lsr>300)

(array([0, 0, 1, 2, 3, 3], dtype=int64),
 array([0, 2, 2, 1, 0, 1], dtype=int64))

In [141]:
a = np.array([22,65,23,55,42,88,96,25,36,55,44])

In [142]:
np.where(a>60)      # find through index number

(array([1, 5, 6], dtype=int64),)

In [143]:
np.where(a<40)

(array([0, 2, 7, 8], dtype=int64),)

In [144]:
import pandas as pd

In [145]:
df = pd.DataFrame({
    'name':['Roshan','Asha','Ganesh'],
    'id':[101,102,104],
    'sal':[224,652,457]
})

In [146]:
df

name   id  sal
0  Roshan  101  224
1    Asha  102  652
2  Ganesh  104  457

In [154]:
df1 = pd.Series([1,2,3], name = 'test')    # create series 

In [155]:
df1

0    1
1    2
2    3
Name: test, dtype: int64

In [157]:
pd.concat([df,df1],axis = 1)

name   id  sal  test
0  Roshan  101  224     1
1    Asha  102  652     2
2  Ganesh  104  457     3

In [158]:
temp = np.array([20,17,25])

In [159]:
temp

array([20, 17, 25])

In [167]:
temps = pd.Series(temp,name = 'DOB')

In [168]:
temps

0    20
1    17
2    25
Name: DOB, dtype: int32

In [169]:
pd.concat((df,temps),axis = 1)

name   id  sal  DOB
0  Roshan  101  224   20
1    Asha  102  652   17
2  Ganesh  104  457   25

In [170]:
lst

array([[[1, 5, 7],
        [2, 3, 8]],

       [[4, 6, 8],
        [6, 8, 7]]])

In [173]:
lst.data