In [2]:
import numpy as np

In [3]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
a = np.arange(15).reshape(3,5)       # reshape create matrix with (3 row and 5 column)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
# shape :- a matrix with n rows and m columns, shape will be (n,m).

a.shape

(3, 5)

In [7]:
# ndim :- the number of axes (dimensions) of the array.

a.ndim

2

In [8]:
a.dtype.name

'int32'

In [9]:
# itemsize :- the size in bytes of each element of the array (ex. here one item = 4 byte)   1 byte = 8 bit

a.itemsize

4

In [10]:
# size:- the total number of elements of the array

a.size

15

In [13]:
# total Bytes calculate in array

a.itemsize * a.size

60

In [11]:
type(a)

numpy.ndarray

In [14]:
b = np.array([24,25,26])

In [15]:
b

array([24, 25, 26])

In [16]:
type(b)

numpy.ndarray

In [17]:
# Array Creation :- There are several ways to create arrays.

a = np.array([2,1,4,5,6])

In [18]:
a

array([2, 1, 4, 5, 6])

In [19]:
b = np.array([12.5,2.7,3.9,45.1])

In [20]:
b

array([12.5,  2.7,  3.9, 45.1])

In [21]:
type(b)

numpy.ndarray

In [22]:
b.dtype

dtype('float64')

In [23]:
a.dtype

dtype('int32')

In [24]:
c = np.array([1.2,2.4,3.5],dtype = 'float32')

In [25]:
c.dtype

dtype('float32')

In [26]:
d = np.array([(10.5,2,6),(2,3,7)])

In [27]:
d

array([[10.5,  2. ,  6. ],
       [ 2. ,  3. ,  7. ]])

In [28]:
ls = np.array([[1,2],[3,4]],dtype = 'complex')

In [29]:
ls

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [32]:
np.zeros((3,4),dtype = 'int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [33]:
np.zeros((3,4),dtype = 'float')

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.zeros((3,4),dtype = 'complex')

array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [35]:
np.ones([3,4],dtype = 'int16')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [38]:
np.empty([2,3])

array([[10.5,  2. ,  6. ],
       [ 2. ,  3. ,  7. ]])

In [40]:
np.empty([4,3],dtype = 'int16')

array([[ 19760, -27181,    350],
       [     0,      0,      0],
       [     0,      0,      3],
       [     2,   8202,   8224]], dtype=int16)

In [41]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [42]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [43]:
np.arange(0,2,0.5)

array([0. , 0.5, 1. , 1.5])

In [46]:
from numpy import pi

In [49]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [52]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [53]:
x = np.linspace(0,2*pi,100)
f = np.sin(x)

In [54]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [61]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [62]:
np.arange(12).reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [64]:
np.arange(24).reshape(2,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

In [69]:
np.arange(100)          # 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [70]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [71]:
# Basic Operations

a = np.array([20,30,40,50])
b = np.arange(4)

In [72]:
a

array([20, 30, 40, 50])

In [73]:
b

array([0, 1, 2, 3])

In [74]:
c = a-b

In [75]:
c

array([20, 29, 38, 47])

In [76]:
c*2

array([40, 58, 76, 94])

In [77]:
c**2

array([ 400,  841, 1444, 2209])

In [79]:
np.sin(a)

array([ 0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [80]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [83]:
a

array([20, 30, 40, 50])

In [84]:
a<35

array([ True,  True, False, False])

In [4]:
# product of two matrix elementwise, matrix A and matrix B---------elementwise product

A = np.array([[1,1],
             [0,1]])

In [5]:
B = np.array([[2,0],
             [3,4]])

In [6]:
A

array([[1, 1],
       [0, 1]])

In [7]:
B

array([[2, 0],
       [3, 4]])

In [8]:
A*B

array([[2, 0],
       [0, 4]])

In [9]:
# product of two matrix, matrix A and matrix B-----------matrix product

A@B

array([[5, 4],
       [3, 4]])

In [10]:
# product of two matrix, matrix A and matrix B-----------matrix product

A.dot(B)

array([[5, 4],
       [3, 4]])

In [11]:
rg = np.random.default_rng(1)  # create instance of default random number generator
rg

Generator(PCG64) at 0x222CB6E4F20

In [15]:
a = np.ones((2,3),dtype = 'int')
b = rg.random((2,3))
a *= 3

In [18]:
b += a

In [19]:
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [23]:
from numpy import pi

a = np.ones(3, dtype = np.int32)
b = np.linspace(0,pi,3)

In [26]:
b.dtype.name

'float64'

In [27]:
a

array([1, 1, 1])

In [28]:
c = a + b

In [29]:
c

array([1.        , 2.57079633, 4.14159265])

In [32]:
d = np.exp(c * 1j)

In [33]:
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [34]:
d.dtype.name

'complex128'

In [37]:
a = rg.random((2,3))

In [42]:
a.sum(),a.min(),a.max()

(2.412007822394087, 0.13404169724716475, 0.7884287034284043)

In [43]:
def f(x,y):
    return 10*x + y

In [44]:
b = np.fromfunction(f,(5,4),dtype = 'int')

In [45]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [48]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [50]:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43
